### PR TITLE
Fixes, refactor and preparation for blog integration

### PR DESCRIPTION
**Pull request by TobiGr**
This PR

- moves the CSS files into a separate directory

- moves the bxslider plugin into a separate directory

- includes some small fixes

- prepares the former `slides-container` (`news-container` now) for a later integration of the blog

### CODE REVIEW

**Comment by TheAssassin** [comment]
Sounds great. I should get to review it until Friday. If not, please notify me earlier, so you don't have to wait 3 weeks again, because that damages your flow pretty badly.

**Comment by TobiGr** [comment]
It's okay when you don't have time to review it. I can work locally and make progress without anything being merged. Don't worry ;) The only thing that damages my work flow is getting no feedback on designs and/or ideas. So I have to wait for it or make my own decisions (not always the best way because I'm not a designer).

My idea about the blog integration was to include a HTML file from the blog's directory. The file should be generated by Jekyll without any problems. The inclusion can be easily done with PHP, Ajax or an iFrame (I prefer to use PHP).

**Comment by TheAssassin** [comment]
Next time you need a review feel free to add me as a reviewer. (If you can't, please tell me and I'll make sure you are going to be able to in the future).

About the inclusion: PHP is not the best idea, that would require a server with PHP to run for the normal page, too, which is most likely undesirable. Especially since the blog is static, too.

I'd suggest a method that I've successfully used in previous projects: Have the blog generate an RSS or Atom feed, and use AJAX and a JS feed parser to work with that info. I think there might even be plugins for jekyll that generate an RSS like JSON file. Please let me know what you think and if you have experience with that. It's a lot less complex than you might expect, and we don't need to run any code on any server, which makes the deployment super easy (could just run on GitHub in theory)

If you should happen to need help, please try to continue to work with a placeholder, wireframe, mockup or something like that, and we'll have a look together.

**Comment by TheAssassin** [comment]
@TobiGr looks good to me, I like the improved structure. Do you plan to update this PR, or should we just merge it right away?

**Comment by TobiGr** [comment]
@TheAssassin It is no problem to update this PR. But how do you want to change the structure.
Do you want to put all CSS (Bootstrap, bxSlider, ...) and all JS files into one directory?

I've already included a feed plugin into the blog. But the information that is included in the feed is not enough to build the whole thing on the main page. So we have to write our own feed in wich we put the required information, then look for a plugin (there are some good one's) and arrange to fit it to our problem. There are some examples for costume feeds, but it's stil a lot of work.

Another option to integrate the blog extract into the main page is moving the main page into the Jekyll environment. This keeps the number of client side scripts as small as possible and that is an advantage for mobile users (speed and traffic/data). Checkout [this](https://github.com/TobiGr/NewPipe-Blog/tree/MAIN_PAGE_INTEGRATION)  branch to see a preview. It works for now, but it is still really messy because I did not have enough time to do a full clean up. I'll do this in the next two weeks. All in all this way should need less time than the feed parser.

**Comment by TheAssassin** [comment]
> But how do you want to change the structure?
> Do you want to put all CSS (Bootstrap, bxSlider, ...) and all JS files into one directory?

What do you mean? I didn't mention any structural changes, in fact, I said that I like how you restructured it.

What additional information do you need? Can you give an example of the feed that has been generated?

I wouldn't attempt to overengineer this too much. Optimizations are done when the requirements for functionality are met.

I think we should discuss that on IRC sometime. I'll try to find that JSON feed plugin thing for Jekyll again, too.

**Comment by TobiGr** [comment]
Oh. I read "I like to improve the structure". Classic fail when it is to late :)
I think everything is ready for merge.

**Pull request merged**
