### PR TITLE
Add blog post about NewPipe 0.14.1

### LINKED ISSUE #97: Add blog post for YouTube Armageddon.
@TobiGr  It was a good idea to create a blogpost about what happened yesterday, so the users will know that v0.14.1 fixed the issue.

### PR DESCRIPTION
**Pull request by TobiGr**
Btw. I added the announcement label to this post. It will be visible in the press kit too.

@theScrabi I hope that everything is correct.

-------
Closes #97

### CODE REVIEW

**Comment by theScrabi** [comment]
Yes it fits.

**Comment by TheAssassin** [comment]
Will update the website ASAP.

**Comment by theScrabi** [comment]
@TobiGr I found an issue: The image is not rendering, and the headline is missing.
bildschirmfoto vom 2018-09-08 22-35-40

Creating this error:
```
      Generating... 
             Error: YAML Exception reading /home/the-scrabi/Projects/website/_posts/2018-09-08-newpipe-0.14.1-released.md: (<unknown>): mapping values are not allowed in this context at line 4 column 27
                    done in 0.627 seconds.
 Auto-regeneration: enabled for '/home/the-scrabi/Projects/website'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
[2018-09-08 22:34:50] ERROR `/css/img/bg_large2.jpg' not found.

```

**Comment by TheAssassin** [comment]
Looking into this right now.

**Pull request merged**
