### PR TITLE
Add blog post about NewPipe 0.14.0 release

### PR DESCRIPTION
**Pull request by TobiGr**
I just finished it, so this is not perfect yet. But you can review, especially the technical things. I assume you guys do not publish the new version before Friday since we should wait for at least one more fix.

For me there is some more stuff to do, before this post can go online:

- [x] optimize and shrink images

- [ ] update images for the press kit

- [ ] fine-tuning and some language improvements

### CODE REVIEW

**Comment by TheAssassin** [comment]
There's way too much raw HTML in that post. The `<p></p>` stuff is probably unnecessary, also GFM (Github flavored Markdown) has an image embedding syntax. Same goes for headlines (`### my heading == <h3>my heading</h3>`). Also, the indentation of block texts is IMO counterintuitive.

**Comment by TheAssassin** [comment]
Took a few minutes to convert all of the HTML into proper GFM (Github flavored Markdown). Didn't review the content yet. Will invite a few people as reviewers.

**Comment by TheAssassin** [comment]
Using the Markdown image syntax was intentional. I don't like to have raw HTML mixed with Markdown. What reason do you have not to use it?

**Comment by TobiGr** [comment]
my bad, I guess it was a bit too late last night...
You are completely right that most HTML tags are superfluous.
I just needed to add classes to the images and therefore I used HTML. I didn't think about the fact that some tiny HTML things are supported in Markdown too.

**Comment by TobiGr** [comment]
> Can these tags perhaps be used "by default", i.e., for all future pictures in the post bodies? Then we could simply use GFM's image syntax again.

Not really. There are different types of images, we embed here and in other posts: 
1) portrait mode screenshots
2) landscape screenshots
3) Images which allow interaction by clicking them to open in a larger size.

Both are handled different. While portrait mode screenshots should only be as height as the viewport and at the same time have not a too large width, landscape screenshots need a larger width. 

I thought about adding an image include which makes it possible to add classes and also additional stuff like galleries etc. This would resolve this problem, but add one Liquid tag instead.

**Comment by TheAssassin** [comment]
Well, it's not a problem, but now it's at least document _why_ you chose to do it like in this thread. That's all I wanted.

**Comment by theScrabi** [comment]
I still don't know if its a good idea to post about new releases.

**Comment by theScrabi** [comment]
Na ... if we don't have a fast release cycle any more, which seems to be the case, than lets do it :)

**Comment by TheAssassin** [comment]
Of course it makes sense to post about new releases. That's what we have the blog for. Subscribers are notified about new releases, we have a nice summary of what has changed, and people's work is credited at least somewhere.

**Comment by theScrabi** [comment]
@TobiGr NewPipe v0.14.0 got released:
https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.14.0

**Comment by TobiGr** [comment]
I saw your that @theScrabi released the new version. Please review and publish the post tomorrow. This enables us to get a feature in the next TWIF. Please leave a link to the post in the TWIF submission thread (somewhere in the F-Droid forums). This has to be done until Thursday which is the deadline for the next TWIF post.
I hope we can get a bit more attention through featured notices in the F-Droid news posts.

**Comment by TheAssassin** [comment]
@TobiGr I'll take care of it, thanks for writing the post. I will proofread and release it ASAP.

**Comment by TobiGr** [comment]
Thanks:+1:

**Comment by TheAssassin** [comment]
Damn! @TobiGr forgot to change the date. Will push an "emergency commit" asap.

**Comment by theScrabi** [comment]
@TheAssassin the release is not done yet, I had to pull it back since @mauriciocolli wanted to fix something before.

**Comment by theScrabi** [comment]
@TobiGr fixed. Version is released again, including the changes from @mauriciocolli.

**Pull request merged**
