### PR TITLE
adding a missing PR

### PR DESCRIPTION
**Pull request by Poolitzer**
The PR is TeamNewPipe/NewPipe#3098, as discussed [here](https://github.com/TeamNewPipe/website/pull/134#issuecomment-589972370)

### CODE REVIEW

**Comment by Poolitzer** [comment]
@B0pol thats it right?

**Comment by B0pol** [comment]
Yeah 🤣
You are funny, you remind me discord changelogs, thank you

**Comment by Poolitzer** [comment]
That is a huge compliment, I really like their changelogs. Thanks man, appreciate it

**Comment by TobiGr** [comment]
Thank you!

**Comment by Poolitzer** [comment]
as always, no problem

**Pull request merged**
