### PR TITLE
add CCC slides

### PR DESCRIPTION
**Pull request by theScrabi**
Hi,

can you please put those slides on the website :)
Thanks :)

rgds schabi

### CODE REVIEW

**Comment by TheAssassin** [comment]
Going to merge this PR manually since I want these slides to be embedded.

**Comment by TobiGr** [comment]
So maybe we should think of another page telling the people how NewPipe works. It could contain the slides and some additional information about contributing and GitHub.
This would mean that we can delete some slides from the gallery.

**Comment by theScrabi** [comment]
Well yea, but that would mean extra work.
So until one of us does that I think it would be enough to just put a link to these slides.

**Comment by TheAssassin** [comment]
Please create an issue for such kind of off-topic ideas, that's going to help us find the information again later.

**Comment by theScrabi** [comment]
Ok

**Pull request merged**
