### PR TITLE
Optimize Header

### PR DESCRIPTION
**Pull request by TobiGr**
This PR includes

- an optimized navigation / menu for small screens
- an improved header
- other small design fixes
- code improvements

### CODE REVIEW

**Comment by TheAssassin** [comment]
Looks  fine. The only thing that looks weird is the NewPipe logo embedded in the upper part of the website.

embedded-newpipe-logo

**Comment by TobiGr** [comment]
As mentioned by @ponypower in [#435](https://github.com/TeamNewPipe/NewPipe/issues/435#issuecomment-279242029), he will add the images and other stuff soon. As long as he did't, I'll use a screenshot of the draft.

**Comment by TheAssassin** [comment]
You could also use one of the images @ponypower uploaded in [#266](https://github.com/TeamNewPipe/NewPipe/issues/266). I am not sure whether there's a white background in the files, but it's quite easy to remove that with any graphics editor.

**Comment by TobiGr** [comment]
Should be fixed now.

**Comment by ponypower** [comment]
I've figured out the small screen design. I'm going to put it together and post the draft for discussion. I will implement some ideas from it to the large screen version. Probably you will get the final files by the end of the week.

**Pull request merged**
