### PR TITLE
where => were

### PR DESCRIPTION
**Pull request by Poolitzer**

### CODE REVIEW

**Comment by TheAssassin** [comment]
Mind to also fix the filename? Or would that change the link then?

**Comment by Poolitzer** [comment]
uhm, does it need fixing? And no, links are taken care of by jekyll

**Comment by gkeegan** [comment]
58.5 instead of 18.5 maybe?

**Comment by TheAssassin** [comment]
@Poolitzer can you please rename the file in this PR quickly? Then we can deploy the fix asap.

**Comment by Poolitzer** [comment]
Not anywhere near my PC im afraid. You can push to the repo though

**Pull request merged**
