### PR TITLE
Add darker container to FAQ pages to make the content less lost

### PR DESCRIPTION
**Pull request by TobiGr**
This adds a grey container around the content. @TheAssassin Is this better than what I've suggested before in https://github.com/TeamNewPipe/website/pull/77#issuecomment-406876912?

For some reason the autoplay tutorial isn't available: https://newpipe.schabi.org/FAQ/tutorials/player-enable-autoplay. The link works locally.
screenshot_2018-08-03 newpipe - a free youtube client

### CODE REVIEW

**Comment by TheAssassin** [comment]
I like this a lot, @TobiGr. It's more decent. Now, the eye-catching part is the actual content. Awesome work.

I'll take the chance to leave some more feedback about the FAQ. I like what you did with those "containers" on the index page which change to text when hovering over them. However, they're a bit non-intuitive. Users who have never used it before might not get where to click, all they see is some images they might not recognize. I've heard this from a user or two already. Is it possible to just put the text below the icons?

**Comment by TobiGr** [comment]
sure. I do this for mobile devices, but can do this for all sizes too.

**Comment by TobiGr** [comment]
grafik

**Comment by theScrabi** [comment]
Nice :)

**Comment by TheAssassin** [comment]
Awesome. Looking forward to the merge!

**Pull request merged**
