### PR TITLE
Add feeds

### LINKED ISSUE #51: Blog as rss fed
I know we aren't using a CMS, but was it still possible to offet our blog as an rss feed?

### PR DESCRIPTION
**Pull request by TobiGr**
With this PR you can find two RSS feeds at[ /rss/:](url)

- `feed.xml` contains every blog post

- `latest.xml` contains the latest blog post

Because we wanted to include our thumbnails into the feed, we need some more data in `images.yml`. This information is required for a valid RSS 2.0:

- type: the file type of the image

- size: the image size in bytes

Closes #51

### CODE REVIEW

**Comment by theScrabi** [comment]
All right. I'll I'd test it on Monday.

**Comment by TheAssassin** [comment]
Interesting, a plugin-free solution. Thanks, looks good to me.

Let's finish discussion in #51 before merging.

**Comment by TobiGr** [comment]
> Let's finish discussion in #51 before merging.

@TheAssassin Feel free to implement the Atom feed, I am busy until Tuesday or maybe even a bit longer.

**Comment by TheAssassin** [comment]
Pushed some preparations, and embedded the feed in the HTML pages.

Can be merged on Monday, unless I get to building the Atom feed. One last feature that really improved the feeds was an NGINX `location` for the RSS feeds to make sure the `Content-Type` header is set correctly.

**Comment by TobiGr** [comment]
@TheAssassin Did you start working on the Atom feeds or should I do it?

> One last feature that really improved the feeds was an NGINX location for the RSS feeds to make sure the Content-Type header is set correctly.

Sounds good! Btw. as I merged the blog and the press kit into another I forgot to delete some files. You just edited the wrong `head.html`. To change the blog's head, you need to edit `blog_head.html`. After I finished #50 I'll do a refactor and clean the whole project. It is long overdue to convert the CSS files into SCSS files.

**Comment by TheAssassin** [comment]
I did not. Please, go ahead and merge it, or feel free to work on the Atom feeds. They're not a hard requirement.

**Comment by TheAssassin** [comment]
By the way, I edited the right `head.html` IMO; I wanted to have the `<link>` on the home page as well.

**Comment by TobiGr** [comment]
In the layouts, I always include `blog_head.html` or `press_head.html`. The one you edited is never used, thus completely useless and can be removed.

>  I wanted to have the <link> on the home page as well.

That's right, but I think you did this in the `index.html`.

**Comment by TheAssassin** [comment]
Ah, I see... well, it's been a couple of days. Thanks for your correction. Will you push a fix, or shall I?

**Comment by TobiGr** [comment]
I'll take a look at the Atom feeds tonight, so I can fix this too.

**Comment by TheAssassin** [comment]
Thanks, @TobiGr. We really appreciate your contributions.

**Comment by TheAssassin** [comment]
I trust your code, but I'm curious, did you run the results through some RSS/Atom validator?

Oh, and if you should wonder why I wanted to write some Atom feed "add-on" -- RSS is not an official standard, whereas Atom has been [standardized by the IETF](https://tools.ietf.org/html/rfc4287). RSS (2) is widely supported, though, and there's usually no compatibility issues, but Atom is the cleaner solution.

**Comment by TobiGr** [comment]
Yes, I used https://validator.w3.org/feed/check.cgi and RSS and Atom are both valid.

Should we add this feed symbol to the blog pages to make subscribing easier? We could do this in the sidebar.

**Comment by TheAssassin** [comment]
Subscribing is already pretty easy IMO, people just need to use the page address. I think some browsers with feed support such as Firefox even notify the user "hey, there's a feed, do you wish to subscribe?".

But I agree we need to advertise the RSS feed in some way for the `<insert Chromium/Chrome market share here>` users that don't use Firefox. If you can integrate the feed symbol, then sure, let's go that way. A text hint might work as well. Please, feel free to implement what you think is best. I guess most Internet users know the feed symbol.

**Comment by TobiGr** [comment]
Should we link to the Atom feed in the head?

**Comment by TobiGr** [comment]
> Should we link to the Atom feed in the head?

I did so. Should be good to merge now.

**Comment by TheAssassin** [comment]
You mean, `<link>`? IIRC you can add more than one tag for multiple feed formats.

**Comment by TobiGr** [comment]
You're right. :D I'll do so.

**Comment by TheAssassin** [comment]
I'll deploy it then. Thanks again.

**Comment by TobiGr** [comment]
Done

**Comment by theScrabi** [comment]
Verry nice 👍

**Pull request merged**
