### PR TITLE
Small fixes and improved bootstrap integration

### PR DESCRIPTION
**Pull request by TobiGr**
Texts for features completed.
Improved design for small screens.

Add all texts and improvements for header.

Some code improvements.

### CODE REVIEW

**Comment by TheAssassin** [comment]
Looks like you're making progress. Could be merged as soon as there's a phone in the phone container (you could use the thing from https://newpipe.schabi.org/).

A few suggestions to make other developers happy:

  - replace all your tabs by 4 spaces (see e.g. https://www.jwz.org/doc/tabs-vs-spaces.html for more information)
  - fix the mixed and in some places inconsistent indentation
  - I see some social media stuff in `index.html`, if you want to enable them, please make them opt-in (two-click) to preserve a high level of privacy for the site users (https://www.wbs-law.de/eng/practice-areas/internet-law/social-media-law/technical-explanation-for-embedding-social-network-buttons-in-a-website-the-two-click-solution/, there's some JavaScript solutions on the internet, you can pick any of them (haven't tested this one but it looks good: https://github.com/panzi/SocialSharePrivacy))

**Comment by TobiGr** [comment]
The social media stuff is disabled and not shown. It's just there, in case we will need it in the future. So if we need it, I will make them opt-in then.
I'll fix the other suggestions as soon as I can.

**Comment by TobiGr** [comment]
Everything should be fixed now.

**Comment by TobiGr** [comment]
Phone added. Should be fine now.

**Comment by TheAssassin** [comment]
Cool. But I just found one more caveat: I cannot find a license for the phone animation. Thus, the distribution and use of the phone stuff might break copyright laws (although I really doubt that). I will merge your PR now, but will create a separate issue for that.

**Comment by theScrabi** [comment]
Uh that phone video also has to be remade, it's a horribly old version shown there :P

**Pull request merged**
