### PR TITLE
Implement new design and Web-API

### PR DESCRIPTION
**Pull request by TobiGr**
This PR brings a new design concept for our landing page. Basically there are tiles ;) and every group of tiles has a topic. I also increased the font size of the texts to get a better readability. Here are two screenshots of the current state:
- [desktop](https://user-images.githubusercontent.com/17365767/37303093-b3595e8e-262d-11e8-859f-f64b391d7998.png)
- [mobile](https://user-images.githubusercontent.com/17365767/37303094-b37f8dfc-262d-11e8-8c0b-9c47ce7898c7.png)

Quick summary of what changed:

- The footer got an update on all sites and now has more links to our sub-pages

- The old `text-2` section got removed and replaced by the tiles.

- The slides "open source" and "free / support NewPipe" are now separate tiles.

- The features' sidebar got an design upgrade for small screens to fit the tiles design.

- I added support for the changes which were made in the Wep-API: https://github.com/TeamNewPipe/web-api/issues/1. I hope it works correctly once these changes are online. 

- The trending screenshot got an update.

### ToDo

- [x] Fix tablet sizes

### CODE REVIEW

**Comment by TheAssassin** [comment]
I like it. The only thing I could find is that the font on the "NewPipe on GitHub" image suffers from aliasing, but otherwise, great job, @TobiGr.

**Comment by TobiGr** [comment]
Oh I forgot to replace it with a .SVG

**Comment by TobiGr** [comment]
Done. 

I just noticed that the open source typo has existed since the first version 😄

**Comment by TheAssassin** [comment]
I will deploy the new API tonight.

**Comment by TobiGr** [comment]
Thanks. 
I can't find any more bugs now. When there are no problems with the API, we can merge it after that.

**Comment by TheAssassin** [comment]
If you can merge the PR, please do. I'll deploy both projects at the same time.

**Comment by TheAssassin** [comment]
Thanks, I'll deploy them right now then.

**Comment by TobiGr** [comment]
Thanks.

**Pull request merged**
