### PR TITLE
Add donation page

### LINKED ISSUE #5: Add page for donations
As @ponypower [mentioned](https://github.com/TeamNewPipe/NewPipe/issues/277#issuecomment-216072533), we need a subpage for donations.
So we have to discuss, which services should be offered and then gather the required information for coding.

### PR DESCRIPTION
**Pull request by TobiGr**
This PR adds the donation page to the website.

Things that are missing, but can be done in a later PR:
- link to Bountysource
- monthly donations
- quotes from other developers to motivate visitors to donate. The purpose of the quotes is to give a good reason for a donation. We should have at least three nice quotes before releasing the website.

Closes #5 and closes TeamNewPipe/NewPipe#747

### CODE REVIEW

**Comment by TheAssassin** [comment]
In general, I'm also not 100% fond of the look. It doesn't blend too well with the rest of the web page. The bold red links in the part below "Thank you" are a bit too bright in my opinion. 

You're on a good way nevertheless. I like the structure of the page so far.

By the way, I just noticed that the link in the footer pointing to the license file is broken, you should change it to `../LICENSE.txt`.

**Comment by TobiGr** [comment]
> In general, I'm also not 100% fond of the look. It doesn't blend too well with the rest of the web page.

I think the main problem is that the main page has more images and has movable parts (parallax, gallery). These things make the page more lightweight and modern. To make the site look more dynamic I used the three different gray backgrounds, but they make the site pretty dark. 
I didn't find good images to add to the donation page. I need an eye-catching image as header to get the users attention. To keep the focus on the site I used the buttons. They are used on many other donation sites too, to persuade the user to make an action and to donate.

> Also, at the moment the buttons are pretty useless, as they're not used, and for Bountysource they're pointless anyway, as the amounts are hardcoded on their website.

As you have to choose a project/feature you want to boost on the Bountysource site, this button was never created to transport specified data. It is only a link to our team site.

> The modal that pops up when clicking on Bitcoin is a bit disruptive, too. How about just putting the address and the QR code right on the page, and replace the money buttons at all? They're not used for any of the donation abilities anyway, the QR code would have to be re-rendered to compose a Bitcoin address with the selected amount, which is not happening either.

In the end I'll re-render the QR code. This won't be a problem. I'll fix this soon. As I already explained the whole donation page is designed to create user interaction. That's why I hide the QR code until the user decides what he/she wants to do. I'd like to hear @ponypower's opinion on this topic, but as he is offline again since three month, we have to find a good solution without him.

> Also, the slideshow doesn't work yet, but that's a minor issue, we'd first have to get more quotes.

Interesting. Everything worked fine with FF54... I'll take a look. Maybe @theScrabi can help us with some quotes.

**Comment by theScrabi** [comment]
@TobiGr ponypower left the project.

**Comment by TheAssassin** [comment]
What's the current state of this branch?

**Comment by TobiGr** [comment]
I accidentally pushed some commits. I'll squash them later. This should be ready to merge until Friday.

**Comment by TheAssassin** [comment]
Great!

But... has anyone set up BountySource and Bitcoin donations yet?

CC @theScrabi

**Comment by TobiGr** [comment]
@TheAssassin I don't think so.
@theScrabi It would be nice if you could send me some nice quotes.

**Comment by TobiGr** [comment]
@TheAssassin Should we wait until the Bountysource account is ready? And we need some more quotes otherwise the carousel does not make sense.

**Comment by theScrabi** [comment]
I would wait.

**Comment by TheAssassin** [comment]
I agree. We should wait for the donation setup to be "up and running" (accounts created, maybe someone sends a donation for testing) before considering the deployment of the donation page.

**Comment by TobiGr** [comment]
It took a little longer and there is one little issue left (the fast-moving phone), but I think it is good enough for a quick design and content review.

**Comment by TheAssassin** [comment]
Scheduled a review for later today.

**Comment by TobiGr** [comment]
At the moment the page looks like [this](https://user-images.githubusercontent.com/17365767/29817535-a6fffbac-8cb8-11e7-9511-695f00096b89.png). [Here](https://user-images.githubusercontent.com/17365767/29817538-ab9c5cb4-8cb8-11e7-8e97-974b6cb2c651.png) I used some other colors. I think it's also good.

**Comment by TheAssassin** [comment]
Just out of curiosity I had a quick look at your first screenshot. You really have to fix that "encrease" to "increases" (that's the correct spelling, and also the correct grammar for this use case). But as said before, I won't have time to have a look until this evening. You can expect a detailed review as soon as I get home (and had dinner).

**Comment by TheAssassin** [comment]
Oh, by the way, I vote for the first color scheme, it's a bit less obtrusive, and the buttons are clearly in focus.

**Comment by TobiGr** [comment]
Don't hurry. We have time to fix everything until Bountysorce is running. 
> It's "increase". Also, the slideshow doesn't work yet, but that's a minor issue, we'd first have to get more quotes.

Btw. I wrote 'increases' before :) but than changed it for you. And the slideshow works. But there is only one item in it.

**Comment by TheAssassin** [comment]
That review is probably outdated. Also, I don't want to be too pedantic about it (just a matter of looking professional by using correct spelling and grammar, please don't take it personal), but in your first screenshot you had "encreases". My note was about replacing the leading "e" by an "i", the trailing "s" was and is still correct. At the moment, it's "encrease", which is now incorrect in two ways. TL;DR: replace it by "increases" and it should be fine.

**Comment by TobiGr** [comment]
Oh yeah. I'm sorry. I should read a little more thoroughly. This is the second time I've made a mistake because I read too fast.

**Comment by TobiGr** [comment]
@theScrabi Can you tell us how long it will take you to set up the BountySource account? I still have some changes to the main page, but they are blocked by this merge request. I'd like to do a refactor of the stylesheet so we can use the base classes for the main page, the press kit and the blog.

**Comment by theScrabi** [comment]
I'm sorry it took me so long. I'll try to get it working today.

**Comment by theScrabi** [comment]
@TobiGr @TheAssassin @mauriciocolli @coffeemakr @BlenderViking  @wb9688 as it seams we have to wait a few days until they enable us as team member (an employe of Bountysource has to unlock us).
You guys can claim to be a team member [here](https://www.bountysource.com/teams/newpipe).

**Comment by wb9688** [comment]
@theScrabi: It says:

>All Team Claims will be processed within 2 business days. Your team
credentials will be verified. Please ensure your GitHub account is linked
to Bountysource and you are a public member of the GitHub organization (if
applicable).

But we aren't all public members of the GitHub organisation. So, can you
add us all first?

**Comment by theScrabi** [comment]
That is right. @TobiGr and @wb9688 got invited.

**Comment by TheAssassin** [comment]
@theScrabi does it mean you expect team members to register there?

**Comment by theScrabi** [comment]
They should.

**Comment by TobiGr** [comment]
@theScrabi Thanks for setting up the account. 
@mauriciocolli @TheAssassin @wb9688 @coffeemakr and all other developers of NewPipe: I would like to put quotes from you on the website that tell people why they should donate. This is intended to motivate them to donate. If one of you guys has a nice and short sentence for me, that would be great.

**Comment by TobiGr** [comment]
Sorry for the delay, but I think this is ready now. We should test Bountysource and add some more quotes before we release.

**Comment by TobiGr** [comment]
I remove the quotes until somebody adds some more. 
@TheAssassin We should bring this online now. What do you think?

**Comment by TheAssassin** [comment]
You can merge it at any time. Please resolve the conflicts, merge it and I'll deploy it.

**Comment by TobiGr** [comment]
OK. I'll do so tomorrow. Just saw that I used the wrong logo again.

**Comment by TobiGr** [comment]
I'll wait for TeamNewPipe/NewPipe#730.

**Comment by TheAssassin** [comment]
What's the current state of this PR? Did anyone manage to get Bountysource work as intended?

**Comment by TobiGr** [comment]
Unfortunately not. I can't even login with my GitHub account right now. We should consider whether we remove Bountysource from our donation page and the `readme` as long as there is no progress on it. I'd like to merge this as soon as possible.
CC @theScrabi

**Comment by theScrabi** [comment]
I doubt it will. As I said we should look for alternatives.

**Comment by TheAssassin** [comment]
Looks good. Please merge asap!

**Comment by TheAssassin** [comment]
Deployed it a minute ago.

**Comment by TobiGr** [comment]
Thanks

**Pull request merged**
