### PR TITLE
Press & Blog Improvements

### PR DESCRIPTION
**Pull request by TobiGr**
Here are some small improvements for the blog and the press kit.

- Most importantly I fixed some false links and onclick actions on the thumbnails

- I moved the post's list of categories to the text container

- Added an experimental support for linking thumbnails in the press kit to their download page. (Just go to the announcements and click the beta logo.) This can be done via the `images.yml`. Use `download:` and the absolute path to the download page / anchor.

### CODE REVIEW

**Comment by TheAssassin** [comment]
Looks really good. 

@theScrabi our logo is GPLv3? That's a real bad license, especially when media are trying to use it, e.g., in articles. Can we change it to some CC license? E.g., CC-By-ND-SA or CC-By-SA?)

@TobiGr the "experimental" linking works very well, looking at the result (I didn't check the code).

**Comment by TheAssassin** [comment]
@TobiGr the "issues" link should be https://github.com/TeamNewPipe/NewPipe/issues?utf8=%E2%9C%93&q=label%3Ameta, this way, GitHub searches for all issues labeled `meta`.

@theScrabi have there been any announcements without the `meta` label`? If yes, we should label them accordingly now.

**Comment by TobiGr** [comment]
We used the `announcement` label, e.g https://github.com/TeamNewPipe/NewPipe/issues/385. But for some reason you can't find them via the search. This must be a bug, because it worked some time ago. That's the reason I only added the incomplete link. I forgot to mention that.

**Comment by TheAssassin** [comment]
@TobiGr I think @theScrabi removed it... that's why it's black, it used to be red.

**Comment by TobiGr** [comment]
Should we use the `meta` label now? 
Btw. What do you think of displaying the number of comments next to its tags? I don't know if we can do this easily with isso, but I'd like to show as often as possible that one can comment :)

**Comment by TobiGr** [comment]
@TheAssassin What do we do with the link? We could add a new label or just use `meta`.

**Comment by TobiGr** [comment]
I think the `meta` label is not helpful. The only interesting thread is about the C34 talk.
I'd prefer to keep it the way it is right now because I'd like to merge :)

**Comment by TobiGr** [comment]
I'd like to merge this asap. 
@TheAssassin @theScrabi Should I re-add the `announcement` label to the tickets?

**Comment by TheAssassin** [comment]
Yeah, good idea. It shouldn't have been deleted.

**Pull request merged**
