### PR TITLE
Add user voice

### PR DESCRIPTION
**Pull request by TobiGr**
I added the user voice from https://github.com/TeamNewPipe/NewPipe/issues/1153#issuecomment-375478646.
@TheAssassin I get the avatar from GitHub. Do you think it is okay to do so or should we prevent tracking by hosting the image?

### CODE REVIEW

**Comment by TheAssassin** [comment]
@TobiGr we could ask for permission to host it ourselves.

CC @Bubu

**Comment by TobiGr** [comment]
Oh yes

**Comment by Bubu** [comment]
Go ahead! :-)

**Comment by TobiGr** [comment]
@Bubu Thanks!
@TheAssassin I think we can merge, can't we?

**Pull request merged**
