### PR TITLE
Remove gallery and add new features view

### PR DESCRIPTION
**Pull request by TobiGr**
Hey guys, 

as already said, I'd like to replace the gallery. That's what I've done.
This PR is in an early state, but I decided to share it with you, because I need some feedback and your ideas.

This is one of the slides. Every slide looks similar. That's why I'd like to have one catching first slide to get the viewers attention.  When you open the side there is a really crappy attempt to use progress bars to persuade the view that NewPipe is fast, small, privacy friendly etc.
@theScrabi @TheAssassin Do you like the idea of using progress bars? If yes, do you have any idea of what we can animate or display to make this slide interesting?

Another idea is to show all services NewPipe supports. But all in all both things are not that good. I'd be happy with anything different :D

As you can see below I wanted to list all projects that support us with offering free services to us and other Open Source projects. Did I forget one?

screenshot-2018-2-23 newpipe - a free youtube client 2
[mobile version](https://user-images.githubusercontent.com/17365767/36619008-86e1fbba-18ed-11e8-8af2-4d8a07754474.png) (too height to show it here)

ToDo:

- [x] first slide
- [x] update screenshots

- [x] fix `.is-flex` 
- [x] tablet version

- [x] JS clean up
- [ ] content check: Is everything correct?

### CODE REVIEW

**Comment by TheAssassin** [comment]
> This is one of the slides. Every slide looks similar. That's why I'd like to have one catching first slide to get the viewers attention. When you open the side there is a really crappy attempt to use progress bars to persuade the view that NewPipe is fast, small, privacy friendly etc.

Looks good to me so far. I didn't build your PR, but the screenshot is promising.

> @theScrabi @TheAssassin Do you like the idea of using progress bars? If yes, do you have any idea of what we can animate or display to make this slide interesting?

Progress bars are great, they show people there's a slideshow. Just be sure to pause the progress bar (and of course, the slideshow as well) when people hover over the area, that's the "expected behavior".

> Another idea is to show all services NewPipe supports. But all in all both things are not that good. I'd be happy with anything different :D

We might list those services separately, at a more "prominent" spot.

**Comment by theScrabi** [comment]
Man this looks so awesome :)

**Comment by TobiGr** [comment]
> We might list those services separately, at a more "prominent" spot.

Yeah, I agree.

> Progress bars are great, they show people there's a slideshow. Just be sure to pause the progress bar (and of course, the slideshow as well) when people hover over the area, that's the "expected behavior".

I think I should have expressed my problems a little further. I was talking about the content which is visible by default. Something like this. I could also image to use some round circles.

features-scetch-lightweight

**Comment by TheAssassin** [comment]
Hm, okay, well, in that case, progress bars are a bit outdated. I'd suggest to use circle graphs instead, perhaps using a JS-based graphing library that animates the whole thing a little.

**Comment by TobiGr** [comment]
Something like this with bigger icons and an animated "progress" when scrolling down to this area?
screenshot-2018-2-25 newpipe - a free youtube client

**Comment by theScrabi** [comment]
But how can we tell those bars, its not like we did benchmark tests?

**Comment by TobiGr** [comment]
We don't say that we are faster/better/... than any other app. We just say that we are fast, etc. 
Btw. can you please go through the slides and look at the texts and tell me whether they are good or I forgot some points.

**Comment by TheAssassin** [comment]
You should increase the values to some random (but fixed) values between 85 and 95 percent.

**Comment by TheAssassin** [comment]
> But how can we tell those bars, its not like we did benchmark tests?

This is marketing. You're allowed to make wild claims. As long as you don't add a possibility to compare these values (e.g., a scale, so that you could compare it to another app's results), it's not lies. But it looks good, and most people don't think too much about such graphs when they see them.

**Comment by TheAssassin** [comment]
@TobiGr what I meant with "animated" is the "initial" animation when the graphs are first viewed, something like [here](http://www.chartjs.org/docs/latest/charts/doughnut.html).

**Comment by TobiGr** [comment]
There are only two things left to do:

- JS and CSS clean up

- Content review from @TheAssassin and @theScrabi. Please go throught it and maybe you find some points we can add or remove.

**Comment by TobiGr** [comment]
Now it's up to you :)

**Comment by TheAssassin** [comment]
Looks good at a first glance. @theScrabi?

**Comment by theScrabi** [comment]
I can't test it right now, but i trust you. If @TheAssassin says its cool, its cool :)

**Pull request merged**
