### PR TITLE
Update to Jekyll 4.1.1

### PR DESCRIPTION
**Pull request by TobiGr**
Don't install dependencies which are only required on Windows.

We were lucky and the migration to Jekyll 4 was improved lately :)

Added some basic info about testing for dead links.

### CODE REVIEW

**Comment by TobiGr** [comment]
Do we need  `Gemfile.lock` or can this file be removed safely?

**Comment by TheAssassin** [comment]
It's recommended: https://bundler.io/rationale.html#checking-your-code-into-version-control

**Comment by TheAssassin** [comment]
Having issues in the Vagrant container with sassc 2.4.0... trying to hack around the issue right now, but it should work in there.

**Comment by TheAssassin** [comment]
```
Gem files will remain installed in /vagrant/vendor/bundle/ruby/2.5.0/gems/sassc-2.4.0 for inspection.
Results logged to /vagrant/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/sassc-2.4.0/gem_make.out

An error occurred while installing sassc (2.4.0), and Bundler cannot continue.
Make sure that `gem install sassc -v '2.4.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  minima was resolved to 2.5.1, which depends on
    jekyll-feed was resolved to 0.15.0, which depends on
      jekyll was resolved to 4.1.1, which depends on
        jekyll-sass-converter was resolved to 2.1.0, which depends on
          sassc

**Comment by TobiGr** [comment]
I've updated to ruby 2.7 for security reasons in https://github.com/TeamNewPipe/website/pull/169/commits/fefcc614a9aaecb5be84e5120e51ee0c201ad98f#diff-e79a60dc6b85309ae70a6ea8261eaf95R80, but your logs say 2.5.0 is used. Maybe this is the problem?

**Comment by TheAssassin** [comment]
Maybe. I didn't get a single warning, error or whatever about this from bundler & Co, which is pretty annoying. I must have missed that in the commits, it's easy to overlook. The Vagrantfile hasn't been updated either. Ruby 2.7.0 is not available in our deployment environment; it would've had to be upgraded to focal (which shouldn't be a problem at all). It's important to me that our environments are kept in sync with whatever we depend on. I've upgraded the Vagrantfile and re-fetched the Docker base image. Building both will reveal if it'll work then.

**Comment by TheAssassin** [comment]
Docker works, Vagrant doesn't, I'm a bit lost but Docker is what's more important at this point. Thanks!

**Pull request merged**
