### PR TITLE
Update download section

### PR DESCRIPTION
**Pull request by TobiGr**
- Removed Beta
- Added feedback request
- Added F-Droid logo to F-Droid carousel and enabled carousel controls

@theScrabi @TheAssassin Do you agree to ask them for feedback? I added a button which links to our issue page, but to no specific ticket. That isn't perfect, because this can easily increase the amount of duplicates. Do you have any better solutions for this or should we only link to the blog?

screenshot_2018-05-10 newpipe - a free youtube client

### CODE REVIEW

**Comment by theScrabi** [comment]
Good question. Thr amount of duplicates indeed increesed a lot.

**Comment by TobiGr** [comment]
We could also do something different to draw the visitor's attention to our FAQ page. It's only a quick sketch, but it's enough to see what I mean: [new download section](https://user-images.githubusercontent.com/17365767/39957228-cee9903c-55ef-11e8-854f-97e0b47989da.jpg)
I am not sure which tutorials we should feature, but we can discuss this later. Every box would link to one tutorial.

**Comment by TheAssassin** [comment]
Looks good to me. Only the F-Droid logo is a bit small.

Regarding the feedback: I'd rather redirect them to GitHub than to the blog. We've had a few suggestions in the blog comments, but @TobiGr had to manually create issues for the promising ones. Also, we don't get any notifications about new comments. Maintenance wise, it's better to tell people to create their issues on GitHub directly.

**Comment by TobiGr** [comment]
>  Also, we don't get any notifications about new comments

@TheAssassin You can [set up notifications](https://posativ.org/isso/docs/configuration/server/#smtp) via e-Mail. Btw. the people at isso just enabled the possibility to preview comments. Unfortunately Martin Zimmermann, the founder of isso, [is busy](https://github.com/posativ/isso/issues/388#issuecomment-364227576) and does not release new versions which could be installed via `pip` easily.

> Maintenance wise, it's better to tell people to create their issues on GitHub directly.

That's a good point. On the other hand, our blog needs no registration and is open for everyone. Maybe we can ask some of the other devs to take a look at the comments too.

_Offtopic:_ Don't we need a disclaimer about which information we keep when someone leaves a comment (server logs, IP addresses used by isso to prevent spam, etc.)?

**Comment by TheAssassin** [comment]
> disclaimer

It'd be a privacy policy, not a disclaimer. And yes, we should probably set something like that up by the 25th.

**Comment by TobiGr** [comment]
Can you take care of the content? I can do the rest.

**Comment by TheAssassin** [comment]
I will try to get you some text within the next week.

**Comment by TobiGr** [comment]
> Maintenance wise, it's better to tell people to create their issues on GitHub directly.

We could also link positive feedback to the blog and bugs, crashes and wishes to GitHub.

**Comment by theScrabi** [comment]
Sounds good.

**Comment by TheAssassin** [comment]
First draft: https://paste.assassinate-you.net/pm3cln0as/woll4r

Please review. Feedback can be sent to me via mail.

**Comment by TobiGr** [comment]
Looks good to me.

> The data is processed and stored only for the purposes described above. We will not share any of the data with third parties. The published data is available on the Internet publicly, so that we can not tell whether third parties will copy them unauthorizedly. We want to state that we do not authorize any of these uses.

You already mentioned it, but maybe we could add that we protect the data in all conscience, but can not ensure complete protection against abuse.

**Comment by TheAssassin** [comment]
By the way, we should not include this document in the Git repository, @TobiGr. I don't want to make it too easy for bots to find it. Therefore I'll also add a robots.txt to exclude it from search engines.

**Pull request closed without merging**
