### PR TITLE
huawei-background-play-solution

### PR DESCRIPTION
**Pull request by gkeegan**
Video for step by step tutorial to allow background audio playing on Huawei devices.

### CODE REVIEW

**Comment by gkeegan** [comment]
File size is large. Feel free to edit the video to keep the repository size down. Maybe change bitrate or resolution?

**Comment by theScrabi** [comment]
Here is the preview of the video.
asdf

@gkeegan you expose a lot about the apps you are using. Are you sure you want to do this?

**Comment by gkeegan** [comment]
Yes

**Comment by TobiGr** [comment]
@gkeegan Thanks again.
I was able to reduce the file size to ~820kB using HandBrake by reducing the frame rate and applying web optimization (72ppi).
I opened #94 which includes the tutorial too. Therefore I'll close this PR.

**Pull request closed without merging**
