### PR TITLE
Change domain name from newpipe.schabi.org to newpipe.net

### PR DESCRIPTION
**Pull request by TobiGr**
Complete moving from https://newpipe.schabi.org to https://newpipe.net

### CODE REVIEW

**Comment by B0pol** [comment]
I think you should not use site.URL but newpipe.net for index urls, isso comments. Otherwise links won't work locally

**Comment by TobiGr** [comment]
I don't face any problems locally. What do you mean exactly?

**Comment by B0pol** [comment]
On the homepage, user feedback: when you click on Neil simpson or Sarah Ann berger name, there is a link to their feedback.

Locally, the link is: 

http://localhost:4000/blog/pinned/NewPipe-needs-feedback/#isso-12
http://localhost:4000/blog/pinned/NewPipe-needs-feedback/#isso-8

As blog comments are not part of the static website, they aren't available locally. That's why I said to use newpipe.net instead of site.url

But anyway, it seems like all comments from this post have been deleted (see https://newpipe.net/blog/pinned/NewPipe-needs-feedback/)
Therefore you should change to the web archive link

https://web.archive.org/web/20201030115227/https://newpipe.schabi.org/blog/pinned/NewPipe-needs-feedback/#isso-8
https://web.archive.org/web/20201030115227/https://newpipe.schabi.org/blog/pinned/NewPipe-needs-feedback/#isso-12

**Review by TheAssassin — APPROVED** [review]

**Comment by TobiGr** [comment]
@B0pol The comments are there. I can see them on newpipe.net. And I don't think it is an issue to have two links which are not working locally as long as they work in production.

**Pull request merged**
