### PR TITLE
Add icons to first slide of the gallery

### PR DESCRIPTION
**Pull request by TobiGr**
This PR

- replaces the placeholders on the first slide in the gallery with Font Awesome icons

- adds images for not in FA included icons

### CODE REVIEW

**Comment by TobiGr** [comment]
Well licenses... That's always a bit annoying (One reason for an imprint by the way, because pasting links to the bottom of the page doesn't look good).

The feather is build on [this](http://www.flaticon.com/free-icon/feather-filled-shape_57869) icon, but I worked on it a lot. It licensed under [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/), so it's no problem.

I didn't know about the issue with the OSI icon. I took it from [here](https://de.icons8.com/web-app/for/all/open%20source) ([CC BY-ND 3.0](https://creativecommons.org/licenses/by-nd/3.0/), a link to the website needs to be provided). So the question is if we violate the OSI guidelines or they are doing.
The problem with the OSI icon is, that the icons and their colors refer to the original design from [NewPipe#277](https://github.com/TeamNewPipe/NewPipe/issues/277#issuecomment-216072533). The whole thing will look crappy if I only change the color of one icon. But changing all colors of the features container seems to be a lot of work. And I don't know if the OSI icon worth this.

**Comment by TheAssassin** [comment]
Those icons don't need a link to the website, even if the author requires it, he licensed it under CC-BY, which means we can just put his name somewhere on the page with a reference to the icon.

As you correctly noticed, they apparently violate the OSI guidelines. Thus, if we used it, we'd violate them, too.

I am not sure why to include the OSI logo anyway, we are not related to the OSI in any way. Since I don't recall, why did you include it anyway? Is it in the old design, too? I don't really think we need it on the page.

**Comment by TobiGr** [comment]
The OSI logo is used in the old design. But I think we can replace the Open Source text with a text about bookmarks or subscriptions. I think both will be implemented soon.

**Comment by TobiGr** [comment]
Something like this? Maybe @theScrabi should check it before I do the commit.
screenshot 14 features

**Comment by TheAssassin** [comment]
You might want to search for an alternative to that feather though. I appreciate your work, but having to mention the author for such a little logo doesn't seem appropriate to me.

**Comment by TobiGr** [comment]
feather_icon
Is this better or do you want something completely different?

**Comment by TheAssassin** [comment]
The question is whether its license does require attribution. You have not given any information about that.

**Comment by TobiGr** [comment]
Painted this quickly. So no license.

**Comment by TheAssassin** [comment]
So it is safe to assume that the file is public domain/CC-0? If yes, we can add that information to a LICENSE.txt or something similar, and it's perfectly fine.

**Comment by TobiGr** [comment]
Shall I make the text "Copyright © NewPipe. All rights reserved" to a link to the LICENSE.txt? 
It's the last line in the footer.

**Comment by TheAssassin** [comment]
No, you should not. But you could add a link like "See also" to that LICENSE.txt.

**Comment by TobiGr** [comment]
*Offtopic:*
The background image we use for the parallax is licensed under CC BY-SA 2.0.
How do we declare this, because it's a background image?

**Comment by theScrabi** [comment]
Couldn't we use the [background image](https://github.com/TeamNewPipe/NewPipe/issues/435#issuecomment-280152665) ponypower designed? I liked it better :/

**Comment by TobiGr** [comment]
I've tried to get some exact details of its design. Unfortunately, he never told me anything about it or uploaded the raw files. He wanted to implement it himself ...
I'll ask him again.

As you can see, I removed the info about "Open Source" and replaced it with "Bookmarks". We wanted to know if it's okay to do so, because this feature isn't completed yet. But if I understood you correctly, it's on the top of your todo list and it will take a while until the website is released.

**Comment by theScrabi** [comment]
Ow well ... keep that open source for a while (also thats importand for me). And that bookmark thing, well i can't tell you when it will be implemented.
So to be honest having bookmarks on top of the list does not mean it's my main goal right now.

**Comment by TobiGr** [comment]
gallery overview_2
@TheAssassin I replaced the OSI icon with an eye, because it fits to the description and the Open Source idea.

Can I take it that the whole repo should be Public Domain?
If yes, is this enough for a license or do I have to add the whole license text?
`All files stored in this GitHub repository at https://github.com/TeamNewPipe/website are Public Domain, CC0 1.0 Universal, unless otherwise explicitly licensed in the file or the directory. For more information about CC0 1.0 Universal see 
https://creativecommons.org/publicdomain/zero/1.0/legalcode`

**Comment by TheAssassin** [comment]
No, that would be even worse unfortunately. Also, the files must not be CC-0 because that would result in problems with the logo, all the other third-party stuff etc. I guess you're not that experienced with how to deal with licenses. The only thing we _could_ put under CC-0 would be the contents and the code that we/you have written. We cannot just declare everything is CC-0. All the third party fonts etc...

Please compile a list of all third-party contents you have used so far, and I'll have a look how we can handle those licenses and if what options we have about our own code.

Also, how about making the texts next to the icons (below the headings) real sentences? They actually sound like sentences already, so upper casing the first letter and adding a full stop in the end wouldn't hurt.

**Comment by TobiGr** [comment]
Yes you are right. My knowledge about handling with licenses is pretty limited. I hope, I'll get what you do, so I can increase it a little.  Here's what I used so far:

__Third party source code / libraries__

Font Awesome
http://fontawesome.io/license/ (not sure which license)

Bootstrap
MIT 

bxSlider
MIT

__Third party images__

img/bg_large2.jpg
CC BY-SA 2.0 by Ken Lee, see [here](https://www.flickr.com/photos/kenlee/3927584727/) for more info

img/nexus6.jpg
(already used on the old website, so I don't know where it's taken from)



<hr>

By the way, I consider putting the bxSlider files into an extra directory. I'm going to do it in the next PR. If I don't get the files of the other background image, I'll rename the current file too.

**Comment by TobiGr** [comment]
@TheAssassin Is there any progress with the license?

**Comment by TheAssassin** [comment]
After reviewing our options, I think it's best to use CC-By-SA for our own code. This is like the "content version" of the GPL, and fits our principle "share it under the same terms". Also, it might advertise our project whenever someone uses content from our project.

You can finish this PR, and I'll edit it after merging to fix licensing on the site.

**Comment by TobiGr** [comment]
I've already added a link to the LICENSE.txt in the footer. I think we can keep it as long as you add the file later.
Nevertheless this PR is ready to merge.

**Comment by TheAssassin** [comment]
I'll put the review on my todo list.

**Comment by TobiGr** [comment]
@TheAssassin Any chance to merge that soon? I've some changes and fixes in the pipeline waiting for this to be merged. 
If you do not have the time now, it's no problem. I'll then take a look at the blog and the donation page. But I want to finish the website as soon as possible so I can focus a little more on Android development and app design.

**Comment by TheAssassin** [comment]
@TobiGr I'm sorry, I got so many GitHub issues, PRs and other stuff I failed to keep track of everything.

I am going t o review it today.

**Comment by TheAssassin** [comment]
I'm going to merge it now. I'll open an issue to remind me of reviewing the licensing situation.

**Pull request merged**
