### PR TITLE
Add import and export tutorial

### PR DESCRIPTION
**Pull request by TobiGr**
Thanks to @princekelly1's draft, I was able to set up the next tutorial.
@TheAssassin @princekelly1 @07typing I need some feedback about the screenshots. Are they useful or not?

screenshot_faq_tutorial_import_export_2

### CODE REVIEW

**Comment by TheAssassin** [comment]
They look okay, but they should have the same height.

**Comment by princekelly1** [comment]
looks great

**Comment by TobiGr** [comment]
> They look okay, but they should have the same height.

Strange. I'll take a look at it.

**Comment by TobiGr** [comment]
I do not have time to take a look at the problem now. (It is a CSS flex issue as far as I can tell).
This tutorial is pending for too long and I'd suggest to merge it now. We can open a ticket for fixing this bug. I would like to link to this tutorial in #109.

**Comment by TheAssassin** [comment]
If you think so, please feel free to do it.

**Comment by TobiGr** [comment]
Yes, we are still in beta, if people are bothered by this, they can jump in and help :)

**Pull request merged**
