### PR TITLE
add link to documentation

### LINKED ISSUE #104: add Link to documentatoin
The [documentation](https://teamnewpipe.github.io/documentation/7) is not perfect, but better then nothing.
I would like to add a link to it onto the website. Right besides the the `FAQ (beta)` link. The link for the moment should be called `Documentation (Alpha)`.

### PR DESCRIPTION
**Pull request by theScrabi**
This will add a link to our documentation:
bildschirmfoto vom 2019-01-31 23-23-30

Fixes #104

### CODE REVIEW

**Comment by TheAssassin** [comment]
Closing in favor of @TobiGr's solution.

**Comment by TobiGr** [comment]
grafik

I fixed the overlapping by removing the brand text and search bar on tablet-like sizes. Also renamed Documentation > Docs

**Comment by TheAssassin** [comment]
I'd rather remove the "Home" button, and would bring back the "NewPipe <subpage>" part.

**Comment by TobiGr** [comment]
> Almost all pages instead prefer the "icon + website title" combination.

That's correct. An icon looks good on the sub pages with the uniform colored navigation bar, but not on the main/home page.

I agree that removing the "NewPipe ..." text is a bad idea. Maybe, we can just hide the subpage's title on tablet sizes. Instead of <logo> NewPipe press/blog etc., we display <logo> NewPipe.

> +1 for removing the issues button.

I'll remove it.

**Comment by TobiGr** [comment]
Closing this in favour of #111. I'll add a proper space management to the nav once #111 is merged.

**Pull request closed without merging**
